// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/13/2025, 11:33:17 AM
const configMerger = require("/home/smaigrot/Portfolio/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/smaigrot/Portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/smaigrot/Portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/smaigrot/Portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/smaigrot/Portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/smaigrot/Portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/smaigrot/Portfolio/plugins/**/*.{js,ts,mjs}","/home/smaigrot/Portfolio/composables/**/*.{js,ts,mjs}","/home/smaigrot/Portfolio/utils/**/*.{js,ts,mjs}","/home/smaigrot/Portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/smaigrot/Portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/smaigrot/Portfolio/app.config.{js,ts,mjs}"] } }));

module.exports = config
